
# Project information
site_name: Juxtapoly
site_url: https://nawinto99.github.io/juxtapoly/
site_author: Naveen Thurimerla
site_description: >-
  Juxtapoly is a tool for comparing data fast. It supports a variety of formats, including CSV, JSON, and RDBMS.

# Repository
repo_name: nawinto99/juxtapoly
repo_url: https://github.com/nawinto99/juxtapoly

# Copyright
copyright: Copyright &copy; 2021 Naveen Thurimerla

# Configuration
theme:
    name: "material"
    logo: assets/favicon.png

    # Static files
    static_templates:
        - 404.html

    # Don't include MkDocs' JavaScript
    include_search_page: false
    search_index_only: true

    language: en
    features:
        - content.tabs.link
        # - navigation.instant
        - navigation.sections
        - navigation.tabs
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
    palette:
        - scheme: default
          primary: amber
          accent: pink
          toggle:
              icon: material/weather-night
              name: Switch to dark mode
        - scheme: slate
          primary: red
          accent: red
          toggle:
              icon: material/weather-sunny
              name: Switch to light mode
    font:
        text: Roboto
        code: Roboto Mono
    favicon: assets/favicon.png
    icon:
        logo: logo

# Plugins
plugins:
    - include-markdown
    - search

# Customization
extra:
    generator: false
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/nawinto99
        - icon: fontawesome/brands/docker
          link: https://hub.docker.com/r/nawinto99/juxtapoly/
        - icon: fontawesome/brands/twitter
          link: https://twitter.com/nawinto99

nav:
    - Home: index.md
    - Getting started:
          - Installation: getting-started.md
          - Usage: usage.md
          - Authors: authors.md
          - Contributing: contributing.md
          - License: license.md
          - Releases:
                - Changelog: changelog.md
